### ISSUE TITLE
Order

### ISSUE THREAD

**Issue by petertwise** [squarecandy/squarecandy-acf-events#2]
A user reported this issue recently:

> I just updated/added a few events, and for some reason one of them is out of chronological order on the events page: https://brendanfaegre.com/events/.  I tried changing data and can't seem to fix or understand it.  See attached screen shot.

**Comment by petertwise** [comment]
Ok, I figured out the bug but have not implemented the solution yet.
There was an end date set to a date in JULY, but then after the end date was set, the "Show end date" checkbox was later unchecked. That left the end date in the database but a confusing UI.

I think we need to implement something that checks on the "save/publish" hook:

- If the "show end date" box is unchecked and there is a value for the End Date field, delete that value
- If the "all day" checkbox is checked and there is a value for Start Time or End Time, delete those values.

**Comment by joehcooper** [comment]
I've just pushed a commit that should resolve this issue. I've also created a pull request for it.
